version: "3"
services:
  database:
    container_name: santa-post-db
    image: postgres:12.9-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5439:5432
    env_file:
      - docker/env/db.env
    volumes:
      - ./dbdata/postgresql/lib:/var/lib/postgresql/data