spring:
  application:
    name: santa-post-ca
  main:
    banner-mode: "off"
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: santa_post_u
    password: bUJfKyGtz2CseV
    maximumPoolSize: 30
    minimumIdle: 5
    dataSourceProperties:
      serverName: ${DATABASE_HOST}
      portNumber: 5432
      databaseName: santa_post_db
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: "classpath:db/migration"

server:
  port: 8099